import 'package:flutter/material.dart';

class LanguageProvider extends ChangeNotifier {
  Locale _currentLocale = const Locale('id', 'ID');

  Locale get currentLocale => _currentLocale;

  void setLanguage(String languageCode) {
    _currentLocale = Locale(languageCode);
    notifyListeners();
  }

  String translate(String key) {
    return _translations[_currentLocale.languageCode]?[key] ??
        _translations['en']?[key] ??
        key;
  }

  static const Map<String, Map<String, String>> _translations = {
    'en': {
      'app_title': 'Weather App',
      'settings': 'Settings',
      'help': 'Help',
      'donation': 'Donation',
      'credits': 'GitHub Credits',
      'language': 'Language',
      'theme': 'Theme',
      'dark_mode': 'Dark Mode',
      'retry': 'Retry',
      'open_settings': 'Open Settings',
      'location_denied': 'Location permission is required to show weather.',
      'location_denied_forever':
          'Location permission is permanently denied. Please enable it in app settings.',
      'location_disabled': 'Location services are disabled. Please enable GPS.',
      'windows_hint':
          'On Windows, please ensure "Let apps access your location" is on in Privacy Settings.',
      'loading_location': 'Loading location...',
      'loading_weather': 'Fetching weather data...',
      'weather_data_empty': 'Weather data is empty',
      'error_occurred': 'Oops! An Error Occurred',
      'no_internet': 'No Internet Connection',
      'refresh_hint': 'Pull down to refresh',
      'help_title': 'Help & Info',
      'help_content':
          'This application uses Open-Meteo API to provide real-time weather information based on your GPS coordinates. The location is used only locally to fetch data and is not stored or shared.',
      'close': 'Close',
      'select_language': 'Select Language',
      'wind_speed': 'Wind Speed',
      'latest_data': 'Latest weather data',
      'sunny': 'Sunny',
      'cloudy': 'Cloudy',
      'foggy': 'Foggy',
      'drizzle': 'Drizzle',
      'freezing_drizzle': 'Freezing Drizzle',
      'rain': 'Rain',
      'freezing_rain': 'Freezing Rain',
      'snow': 'Snow',
      'snow_grains': 'Snow Grains',
      'heavy_rain': 'Heavy Rain',
      'snow_showers': 'Snow Showers',
      'thunderstorm': 'Thunderstorm',
      'unknown': 'Unknown',
    },
    'id': {
      'app_title': 'Aplikasi Cuaca',
      'settings': 'Pengaturan',
      'help': 'Bantuan',
      'donation': 'Donasi',
      'credits': 'Kredit GitHub',
      'language': 'Bahasa',
      'theme': 'Tema',
      'dark_mode': 'Mode Gelap',
      'retry': 'Coba Lagi',
      'open_settings': 'Buka Pengaturan',
      'location_denied': 'Izin lokasi diperlukan untuk menampilkan cuaca.',
      'location_denied_forever':
          'Izin lokasi ditolak permanen. Silakan aktifkan di pengaturan aplikasi.',
      'location_disabled': 'Layanan lokasi tidak aktif. Aktifkan GPS.',
      'windows_hint':
          'Di Windows, pastikan "Let apps access your location" aktif di Pengaturan Privasi.',
      'loading_location': 'Memuat lokasi...',
      'loading_weather': 'Mengambil data cuaca...',
      'weather_data_empty': 'Data cuaca kosong',
      'error_occurred': 'Oops! Terjadi Kesalahan',
      'no_internet': 'Tidak Ada Koneksi Internet',
      'refresh_hint': 'Tarik ke bawah untuk memperbarui',
      'help_title': 'Bantuan & Info',
      'help_content':
          'Aplikasi ini menggunakan API Open-Meteo untuk menyediakan informasi cuaca waktu nyata berdasarkan koordinat GPS Anda. Lokasi hanya digunakan secara lokal untuk mengambil data dan tidak disimpan atau dibagikan.',
      'close': 'Tutup',
      'select_language': 'Pilih Bahasa',
      'wind_speed': 'Kecepatan Angin',
      'latest_data': 'Data cuaca terkini',
      'sunny': 'Cerah',
      'cloudy': 'Berawan',
      'foggy': 'Berkabut',
      'drizzle': 'Gerimis',
      'freezing_drizzle': 'Gerimis Beku',
      'rain': 'Hujan',
      'freezing_rain': 'Hujan Beku',
      'snow': 'Salju',
      'snow_grains': 'Butiran Salju',
      'heavy_rain': 'Hujan Lebat',
      'snow_showers': 'Hujan Salju',
      'thunderstorm': 'Badai Petir',
      'unknown': 'Tidak diketahui',
    },
    'zh': {
      'app_title': '天气助手',
      'settings': '设置',
      'help': '帮助',
      'donation': '打赏',
      'credits': 'GitHub 贡献者',
      'language': '语言',
      'theme': '主题',
      'dark_mode': '深色模式',
      'retry': '重试',
      'open_settings': '打开设置',
      'location_denied': '需要位置权限才能显示天气信息。',
      'location_denied_forever': '位置权限已被永久拒绝。请在设置中开启。',
      'location_disabled': '位置服务已关闭。请开启 GPS。',
      'windows_hint': '在 Windows 上，请确保在隐私设置中开启“允许应用访问位置”。',
      'loading_location': '正在定位...',
      'loading_weather': '正在获取天气数据...',
      'weather_data_empty': '天气数据为空',
      'error_occurred': '糟糕！发生错误',
      'no_internet': '无网络连接',
      'refresh_hint': '下拉刷新',
      'help_title': '帮助与信息',
      'help_content':
          '本应用使用 Open-Meteo API，根据您的 GPS 坐标提供实时天气信息。位置信息仅用于本地获取数据，不会被存储或分享。',
      'close': '关闭',
      'select_language': '选择语言',
      'wind_speed': '风速',
      'latest_data': '最新天气数据',
      'sunny': '晴朗',
      'cloudy': '多云',
      'foggy': '有雾',
      'drizzle': '毛毛雨',
      'freezing_drizzle': '冻毛毛雨',
      'rain': '下雨',
      'freezing_rain': '冻雨',
      'snow': '下雪',
      'snow_grains': '雪粒',
      'heavy_rain': '大雨',
      'snow_showers': '阵雪',
      'thunderstorm': '雷暴',
      'unknown': '未知',
    },
    'ja': {
      'app_title': 'お天気アプリ',
      'settings': '設定',
      'help': 'ヘルプ',
      'donation': '寄付',
      'credits': 'GitHub クレジット',
      'language': '言語',
      'theme': 'テーマ',
      'dark_mode': 'ダークモード',
      'retry': '再試行',
      'open_settings': '設定を開く',
      'location_denied': '天気情報を表示するには位置情報の許可が必要です。',
      'location_denied_forever': '位置情報の許可が永久に拒否されました。設定から有効にしてください。',
      'location_disabled': '位置情報サービスが無効です。GPSを有効にしてください。',
      'windows_hint':
          'Windowsでは、プライバシー設定で「アプリに位置情報のアクセスを許可する」がオンになっていることを確認してください。',
      'loading_location': '位置情報を読み込み中...',
      'loading_weather': '天気データを取得中...',
      'weather_data_empty': '天気データがありません',
      'error_occurred': 'エラーが発生しました',
      'no_internet': 'インターネット接続がありません',
      'refresh_hint': '下にスワイプして更新',
      'help_title': 'ヘルプと情報',
      'help_content':
          'このアプリは Open-Meteo API を使用して、GPS 座標に基づいたリアルタイムの天気情報を提供します。位置情報はデータ取得のためにローカルでのみ使用され、保存や共有はされません。',
      'close': '閉じる',
      'select_language': '言語を選択',
      'wind_speed': '風速',
      'latest_data': '最新の天気データ',
      'sunny': '晴れ',
      'cloudy': '曇り',
      'foggy': '霧',
      'drizzle': '霧雨',
      'freezing_drizzle': '着氷性の霧雨',
      'rain': '雨',
      'freezing_rain': '着氷性の雨',
      'snow': '雪',
      'snow_grains': '霧雪',
      'heavy_rain': '大雨',
      'snow_showers': '雪のしゅう雨',
      'thunderstorm': '雷雨',
      'unknown': '不明',
    },
    'ko': {
      'app_title': '날씨 정보',
      'settings': '설정',
      'help': '도움말',
      'donation': '후원',
      'credits': 'GitHub 크레딧',
      'language': '언어',
      'theme': '테마',
      'dark_mode': '다크 모드',
      'retry': '재시도',
      'open_settings': '설정 열기',
      'location_denied': '날씨를 표시하려면 위치 권한이 필요합니다.',
      'location_denied_forever': '위치 권한이 영구적으로 거부되었습니다. 설정에서 활성화해 주세요.',
      'location_disabled': '위치 서비스가 비활성화되었습니다. GPS를 켜주세요.',
      'windows_hint':
          'Windows에서는 개인정보 설정에서 "앱에서 내 위치에 액세스하도록 허용"이 켜져 있는지 확인하세요.',
      'loading_location': '위치 로딩 중...',
      'loading_weather': '날씨 데이터 가져오는 중...',
      'weather_data_empty': '날씨 데이터가 없습니다',
      'error_occurred': '오류가 발생했습니다',
      'no_internet': '인터넷 연결 없음',
      'refresh_hint': '아래로 당겨서 새로고침',
      'help_title': '도움말 및 정보',
      'help_content':
          '이 애플리케이션은 Open-Meteo API를 사용하여 GPS 좌표를 기반으로 실시간 날씨 정보를 제공합니다. 위치 정보는 데이터를 가져오는 데에만 로컬로 사용되며 저장되거나 공유되지 않습니다.',
      'close': '닫기',
      'select_language': '언어 선택',
      'wind_speed': '풍속',
      'latest_data': '최신 날씨 데이터',
      'sunny': '맑음',
      'cloudy': '흐림',
      'foggy': '안개',
      'drizzle': '이슬비',
      'freezing_drizzle': '얼어붙는 이슬비',
      'rain': '비',
      'freezing_rain': '얼어붙는 비',
      'snow': '눈',
      'snow_grains': '싸라기눈',
      'heavy_rain': '폭우',
      'snow_showers': '소나기성 눈',
      'thunderstorm': '뇌우',
      'unknown': '알 수 없음',
    },
    'ar': {
      'app_title': 'تطبيق الطقس',
      'settings': 'الإعدادات',
      'help': 'مساعدة',
      'donation': 'تبرع',
      'credits': 'حقوق GitHub',
      'language': 'اللغة',
      'theme': 'المظهر',
      'dark_mode': 'الوضع المظلم',
      'retry': 'إعادة المحاولة',
      'open_settings': 'افتح الإعدادات',
      'location_denied': 'إذن الموقع مطلوب لإظهار الطقس.',
      'location_denied_forever':
          'تم رفض إذن الموقع بشكل دائم. يرجى تفعيله في إعدادات التطبيق.',
      'location_disabled':
          'خدمات الموقع معطلة. يرجى تفعيل نظام تحديد المواقع (GPS).',
      'windows_hint':
          'على Windows، يرجى التأكد من تفعيل "السماح للتطبيقات بالوصول إلى موقعك" في إعدادات الخصوصية.',
      'loading_location': 'جاري تحميل الموقع...',
      'loading_weather': 'جاري جلب بيانات الطقس...',
      'weather_data_empty': 'بيانات الطقس فارغة',
      'error_occurred': 'عذراً! حدث خطأ',
      'no_internet': 'لا يوجد اتصال بالإنترنت',
      'refresh_hint': 'اسحب للأسفل للتحديث',
      'help_title': 'المساعدة والمعلومات',
      'help_content':
          'يستخدم هذا التطبيق واجهة برمجة تطبيقات Open-Meteo لتوفير معلومات الطقس في الوقت الفعلي بناءً على إحداثيات GPS الخاصة بك. يتم استخدام الموقع محليًا فقط لجلب البيانات ولا يتم تخزينه أو مشاركته.',
      'close': 'إغلاق',
      'select_language': 'اختر اللغة',
      'wind_speed': 'سرعة الرياح',
      'latest_data': 'أحدث بيانات الطقس',
      'sunny': 'مشمس',
      'cloudy': 'غائم',
      'foggy': 'ضبابي',
      'drizzle': 'رذاذ',
      'freezing_drizzle': 'رذاذ متجمد',
      'rain': 'مطر',
      'freezing_rain': 'مطر متجمد',
      'snow': 'ثلج',
      'snow_grains': 'حبيبات ثلجية',
      'heavy_rain': 'مطر غزير',
      'snow_showers': 'زخات ثلجية',
      'thunderstorm': 'عاصفة رعدية',
      'unknown': 'غير معروف',
    },
    'ru': {
      'app_title': 'Погода',
      'settings': 'Настройки',
      'help': 'Помощь',
      'donation': 'Пожертвования',
      'credits': 'Благодарности GitHub',
      'language': 'Язык',
      'theme': 'Тема',
      'dark_mode': 'Темная тема',
      'retry': 'Повторить',
      'open_settings': 'Открыть настройки',
      'location_denied':
          'Требуется доступ к местоположению для отображения погоды.',
      'location_denied_forever':
          'Доступ к местоположению навсегда запрещен. Включите его в настройках приложения.',
      'location_disabled': 'Службы местоположения отключены. Включите GPS.',
      'windows_hint':
          'В Windows убедитесь, что параметр «Разрешить приложениям доступ к вашему местоположению» включен в настройках конфиденциальности.',
      'loading_location': 'Загрузка местоположения...',
      'loading_weather': 'Получение прогноза...',
      'weather_data_empty': 'Данные о погоде отсутствуют',
      'error_occurred': 'Ой! Произошла ошибка',
      'no_internet': 'Нет подключения к интернету',
      'refresh_hint': 'Потяните вниз, чтобы обновить',
      'help_title': 'Помощь и инфо',
      'help_content':
          'Это приложение использует Open-Meteo API для предоставления информации о погоде в реальном времени на основе ваших координат GPS. Местоположение используется только локально для получения данных и не сохраняется и не передается.',
      'close': 'Закрыть',
      'select_language': 'Выберите язык',
      'wind_speed': 'Скорость ветра',
      'latest_data': 'Последние данные',
      'sunny': 'Ясно',
      'cloudy': 'Облачно',
      'foggy': 'Туман',
      'drizzle': 'Морось',
      'freezing_drizzle': 'Ледяная морось',
      'rain': 'Дождь',
      'freezing_rain': 'Ледяной дождь',
      'snow': 'Снег',
      'snow_grains': 'Снежная крупа',
      'heavy_rain': 'Ливень',
      'snow_showers': 'Снежные ливни',
      'thunderstorm': 'Гроза',
      'unknown': 'Неизвестно',
    },
    'hi': {
      'app_title': 'मौसम ऐप',
      'settings': 'सेटिंग्स',
      'help': 'सहायता',
      'donation': 'दान',
      'credits': 'गिटहब क्रेडिट',
      'language': 'भाषा',
      'theme': 'थीम',
      'dark_mode': 'डार्क मोड',
      'retry': 'पुनः प्रयास करें',
      'open_settings': 'सेटिंग्स खोलें',
      'location_denied': 'मौसम दिखाने के लिए स्थान अनुमति आवश्यक है।',
      'location_denied_forever':
          'स्थान की अनुमति स्थायी रूप से अस्वीकार कर दी गई है। कृपया इसे ऐप सेटिंग्स में सक्षम करें।',
      'location_disabled': 'स्थान सेवाएँ अक्षम हैं। कृपया GPS सक्षम करें।',
      'windows_hint':
          'विंडोज़ पर, कृपया सुनिश्चित करें कि गोपनीयता सेटिंग्स में "ऐप्स को आपके स्थान तक पहुंचने दें" चालू है।',
      'loading_location': 'स्थान लोड हो रहा है...',
      'loading_weather': 'मौसम डेटा प्राप्त किया जा रहा है...',
      'weather_data_empty': 'मौसम डेटा खाली है',
      'error_occurred': 'ओह! एक त्रुटि हुई',
      'no_internet': 'कोई इंटरनेट कनेक्शन नहीं',
      'refresh_hint': 'ताज़ा करने के लिए नीचे खींचें',
      'help_title': 'सहायता और जानकारी',
      'help_content':
          'यह एप्लिकेशन आपके जीपीएस निर्देशांक के आधार पर वास्तविक समय में मौसम की जानकारी प्रदान करने के लिए ओपन-मेटियो एपीआई का उपयोग करता है। स्थान का उपयोग केवल डेटा प्राप्त करने के लिए स्थानीय स्तर पर किया जाता है और इसे संग्रहीत या साझा नहीं किया जाता है।',
      'close': 'बंद करें',
      'select_language': 'भाषा चुनें',
      'wind_speed': 'हवा की गति',
      'latest_data': 'नवीनतम मौसम डेटा',
      'sunny': 'धूप',
      'cloudy': 'बादल',
      'foggy': 'धुंध',
      'drizzle': 'बूंदाबांदी',
      'freezing_drizzle': 'जमने वाली बूंदाबांदी',
      'rain': 'बारिश',
      'freezing_rain': 'जमने वाली बारिश',
      'snow': 'बर्फ',
      'snow_grains': 'बर्फ के दाने',
      'heavy_rain': 'भारी बारिश',
      'snow_showers': 'बर्फ की बौछार',
      'thunderstorm': 'आंधी',
      'unknown': 'अज्ञात',
    },
  };
}
